/* File Name  : error.js
 * Created By : Vishnu Satheesh
 * Date       : Oct 20 2025
 * Purpose    : Holds common error codes for the App
 */

module.exports = Object.freeze({
    /****************REGISTRATION MODULE : STARTS FROM 100 ********************/

    NO_ERROR: 0,
    SERVER_ERROR: 100,
    MISSING_PARAMETERS: 101,
    USERNAME_EXISTS: 102,
    USERNAME_DOESNT_EXISTS: 103,
    FAILED_TO_SET_PASSWORD: 104,
    INVALID_CREDENTIALS: 105,
    FAILED_TO_LOGIN: 106,
    USER_NOT_FOUND: 107,
    FAILED_TO_UPDATE_USER: 108,
    PROJECT_NAME_EXISTS: 109,
    FAILED_TO_CREATE_PROJECT: 110,
    PROJECT_NOT_FOUND: 111,
    INVALID_CUSTOMER: 112,
    FAILED_TO_UPDATE_PROJECT: 113,
    FAILED_TO_CREATE_TEAM: 114,
    TEAM_NOT_FOUND: 115,
    FAILED_TO_UPDATE_TEAM: 116,
    STAGES_NOT_FOUND: 117,
    FAILED_TO_CREATE_STAGE: 118,
    FAILED_TO_UPDATE_STAGE: 119,
    FAILED_TO_CREATE_TRANSACTION: 120,
    TRANSACTIONS_NOT_FOUND: 121,
    FAILED_TO_UPDATE_TRANSACTION: 122,
    FAILED_TO_CREATE_REQUEST: 123,
    FAILED_TO_UPDATE_REQUEST: 124,
    REQUEST_NOT_FOUND: 125,
    FAILED_TO_DELETE_REQUEST: 126,
    ERROR_GENERATING_INVOICE: 127,

    SOMETHING_WENT_WRONG: 500,
    FAILED_TO_UPLOAD_IMAGE: 700,
});
