/* File Name  : error.js
 * Created By : Vishnu Satheesh
 * Date       : Oct 20 2025
 * Purpose    : Holds common error codes for the App
 */

module.exports = Object.freeze({
    /****************REGISTRATION MODULE : STARTS FROM 100 ********************/

    NO_ERROR: 0,
    SERVER_ERROR: 100,
    MISSING_PARAMETERS: 101,
    USERNAME_EXISTS: 102,
    USERNAME_DOESNT_EXISTS: 103,
    FAILED_TO_SET_PASSWORD: 104,
    INVALID_CREDENTIALS: 105,
    FAILED_TO_LOGIN: 106,
    USER_NOT_FOUND: 107,
    FAILED_TO_UPDATE_USER: 108,
    PROJECT_NAME_EXISTS: 109,
    PROJECT_NOT_FOUND: 110,
    INVALID_CUSTOMER: 111,
    FAILED_TO_UPDATE_PROJECT: 112,
    FAILED_TO_CREATE_TEAM: 113,
    TEAM_NOT_FOUND: 114,
    FAILED_TO_UPDATE_TEAM: 115,
    STAGES_NOT_FOUND: 116,
    FAILED_TO_CREATE_STAGE: 117,
    FAILED_TO_UPDATE_STAGE: 118,
    FAILED_TO_CREATE_TRANSACTION: 119,
    TRANSACTIONS_NOT_FOUND: 120,
    FAILED_TO_UPDATE_TRANSACTION: 121,

    SOMETHING_WENT_WRONG: 500,
});
